_target_: federated_datasets.cifar100_dataset.Cifar100Dataset
base_path: home
data_sources:
  test_map_file:
  - /home/skorik/RoPOFL/cifar100/images/test_map_file.csv
  train_map_file:
  - /home/skorik/RoPOFL/cifar100/images/train_map_file.csv
mode: train
