_target_: federated_datasets.food101_dataset.Food101Dataset
base_path: data
data_sources:
  train_map_file:
    - /data/image_data/food101/image_data/food101_train.csv
  test_map_file:
    - /data/image_data/food101/image_data/food101_test_map_file.csv
mode: train
max_samples: null
